### ISSUE TITLE
Version 1.0.2 Is Not Published to atom.io Package Registry

### ISSUE THREAD

**Issue by chhch** [farcaller/typewriter-scroll#5]
Version 1.0.0 is still listed in the atom.io package registry, see image below.

![typewriter-scroll-version](https://user-images.githubusercontent.com/14316947/39932310-176f9e4c-5540-11e8-9d5d-5a969cb18c04.png)

Please publish [manually](https://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#publishing-a-package-manually) the new version 1.0.2. (More about this topic in the [publishing section](https://flight-manual.atom.io/hacking-atom/sections/publishing/#publish-your-package).)

**Comment by chhch** [comment]
Please also start the publishing process. You have to perform the following steps on the `master` branch:

1. Delete invalid remote tag: `git push --delete origin v1.0.2`
2. Move local tag: `git tag -f v1.0.2`
4. Push local tag to remote: `git push origin master --tags` 
5.  Execute `apm publish --tag v1.0.2`

**Comment by farcaller** [comment]
Should be done now, thanks for a nag.

(I don't have atom installed anymore, so it took some time to go through the hoops)
